# render.yaml

services:
  # This defines your web service
  - type: web
    name: mytestSCIM # Or whatever you named it in Render
    env: node
    plan: free # Or your current plan
    buildCommand: "npm install"
    startCommand: "node server.js"
    
    headers:
      - path: "/*"
        name: "X-Frame-Options"
        value: ""
